### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by PJUllrich** [bitfo/ectorange#5]
Hey @davydog187 👋 

I had a quick look and would like to share some thoughts:

1. I agree with you that this project could/should support all [Postgres Ranges](https://www.postgresql.org/docs/current/rangetypes.html#RANGETYPES-BUILTIN). That would be better than having 6 different libraries. Maybe rename it to `ecto_ranges` if you decide to go ahead with this?
2. I see that you hard-code the inclusive/exclusive flags. You could expose them, but default to `true`, to make this library more generic to all kinds of use-cases. 
3. I don't see a problem with using `Postgrex.Range` as an underlying data structure since MySQL doesn't seem to support ranges anyway. So, I guess it's okay to limit this library for Postgres only.
4. To round off this library, a small example in the Readme would be nice that explains e.g. how to use this in an Ecto schema + migration.
5. For the future: It would be really cool if this library would support some operators for working with ranges in Postgres, like e.g. the `overlaps &&` operator. Then, one could use that operator instead of using a `fragment(...)`!

I hope this helps a bit :) Let me know if you want any help with this and I'll gladly contribute!

**Comment by davydog187** [comment]
Thank you @PJUllrich for the thoughtful writeup! I will respond to each directly below, and maybe from there we can break out into issues.

> I agree with you that this project could/should support all [Postgres Ranges](https://www.postgresql.org/docs/current/rangetypes.html#RANGETYPES-BUILTIN). That would be better than having 6 different libraries. Maybe rename it to ecto_ranges if you decide to go ahead with this?

Agreed, and `Ecto.Ranges` seems like a good name, or should we avoid polluting the `Ecto` namespace and do `EctoRanges`?

> I see that you hard-code the inclusive/exclusive flags. You could expose them, but default to true, to make this library more generic to all kinds of use-cases.

Inclusivity is not hardcoded, but rather inherited from the semantics of `Date.Range.t()`, which is an inclusive range. Users are free to pass `%Postgrex.Range{}` with exclusive endpoints and it should work just fine. My thought process was that this library should align as closely to the semantics of Elixir as much as possible. This raises two questions though

1. Should we introduce a type just for unbounded ranges, and return `Date.Range.t()` and friends in the case that it is bounded? Or is such a union type a difficult API to work with?
2. Date.Range.t() and all range types now support steps, which we cannot support as they are not serializable into the postgres range type. We should probably treat any stepped range as an error

> I don't see a problem with using Postgrex.Range as an underlying data structure since MySQL doesn't seem to support ranges anyway. So, I guess it's okay to limit this library for Postgres only.

Agreed, this is a Postgres library only as we are coupled to the underlying ecto type

> To round off this library, a small example in the Readme would be nice that explains e.g. how to use this in an Ecto schema + migration.

For sure! Will happen once I stabilize the API

> For the future: It would be really cool if this library would support some operators for working with ranges in Postgres, like e.g. the overlaps && operator. Then, one could use that operator instead of using a fragment(...)!

I did not think of this, excellent idea! We are doing something similar in my other library, [timescale](https://github.com/bitfo/timescale)

**Comment by davydog187** [comment]
And @PJUllrich i would love your help! I can break these out into issues and we can start collaborating!

**Comment by PJUllrich** [comment]
Hey @davydog187, here I'm getting back to you regarding this:

1. `Ecto.Ranges` vs `EctoRanges`: I'd suggest following [EctoEnum's](https://github.com/gjaldon/ecto_enum) approach and separate this library from `Ecto`. So, I'd suggest using `EctoRanges`. This would allow the ecto library to integrate this library eventually, if they'd ever decide to. If we'd call it `Ecto.Ranges`, there'd be a name collision between this library and any code they'd implement.
2. Ah, yes. Makes sense! Regarding your questions:
    1. I'd argue against returning different types. If you have an `:integer`-field, you don't expect to receive a `:float`-field back. So, I'd suggest to **always** return a `Date.Range.t()` which matches nicely the `:daterange` field type. I think we should convert unbounded `Postgrex.Range.t()` structs into bounded `Date.Range.t()` first (As you do already in `normalize_upper(%Postgrex.Range{})`). 
    2. Agreed. Stepped ranges are not supported in Postgres anyways, so let's block what we can't store in the DB.

For the rest: Cool! Seems like we're well aligned there :) 

If you don't mind, I'll take the liberty to break out some things into different tickets so that we can organise our collaboration better 💪 I'll do so only after work, so feel free to break them out yourself if you beat me to it :)

**Comment by PJUllrich** [comment]
Ok, this is a bit discouraging: I looked at the [Postgrex.Range](https://github.com/elixir-ecto/postgrex/blob/28e36907e7a8e2ec95337b28d9e7667454fcd1dc/lib/postgrex/builtins.ex#L51) definition and from the docs, it seemed like we could just dump _any_ type in there. So, `utc_datetime`, `naive_datetime`, `int2`, `int4`, etc. So, I tried to store a `Postgrex.Range` with UTC DateTimes for lower and upper bounds, but sadly, `Postgrex.Range` only supports `Date{}` structs for those fields 😞 

If we wanted to offer different ranges than a `daterange`, we'd need to extend the [Postgrex.Range](https://github.com/elixir-ecto/postgrex/blob/28e36907e7a8e2ec95337b28d9e7667454fcd1dc/lib/postgrex/extensions/range.ex#L57) extension with encodings for the other types. However, I have **no** clue how to encode **any** type to binary and send it to Postgres :D 

I'm not sure whether you do? Also, do you think it would be worth the effort if one can also store two different fields in a schema and combine them using pure SQL like I did in my post?

**Comment by davydog187** [comment]
> I'd argue against returning different types. If you have an :integer-field, you don't expect to receive a :float-field back. So, I'd suggest to always return a Date.Range.t() which matches nicely the :daterange field type. I think we should convert unbounded Postgrex.Range.t() structs into bounded Date.Range.t() first (As you do already in normalize_upper(%Postgrex.Range{})).

That's fair, but we can't do that as you can't have unbounded `Date.Range.t()`, while you can have unbounded `Postgrex.Range.t()`. Its desirable to support unbounded ranges to add features where you want to have a range that goes from "today until the end of time"

Love the updates! Thank you for being so interested in helping!

**Comment by PJUllrich** [comment]
Ah yes, you're right! What do you think, should we then always return `Postgrex.Range.t()` maybe? That would work for all ranges.

**Comment by davydog187** [comment]
I've broken out operators and multi ranges into separate issues. Closing this
